#pragma once

#define VIAL_KEYBOARD_UID {0x0B, 0xD4, 0x62, 0x0E, 0x3D, 0xBF, 0xCD, 0xB4}

#define NO_ACTION_ONESHOT

#define VIAL_UNLOCK_COMBO_ROWS { 0, 4 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

#define WS2812_DI_PIN F1

#define RGBLIGHT_LED_COUNT 18
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_MODE_RAINBOW_SWIRL
#define RGBLIGHT_MODE_SNAKE
#define RGBLIGHT_MODE_KNIGHT
#define RGBLIGHT_MODE_CHRISTMAS
#define RGBLIGHT_MODE_STATIC_GRADIENT
#define RGBLIGHT_MODE_TWINKLE

#define RGBLIGHT_SLEEP

#define OLED_FONT_H "keyboards/lxiii/r1/common/glcdfont.c"