#pragma once

#define VIAL_KEYBOARD_UID {0x0B, 0xD4, 0x62, 0x0E, 0x3D, 0xBF, 0xCD, 0xB4}

#define NO_ACTION_ONESHOT
#define NO_ACTION_TAPPING

#define VIAL_UNLOCK_COMBO_ROWS { 0, 4 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

#define WS2812_DI_PIN F1

#define RGBLIGHT_LED_COUNT 18
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD

#define RGBLIGHT_SLEEP