LTO_ENABLE = yes

# disable defaults
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no

# esoteric for most people
KEY_OVERRIDE_ENABLE = no
LEADER_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
COMBO_ENABLE = no

# not applicable
AUDIO_ENABLE = no
MIDI_ENABLE = no
UNICODE_ENABLE = no
BLUETOOTH_ENABLE = no
SPLIT_KEYBOARD = no

# most common options
BOOTMAGIC_ENABLE = yes
EXTRAKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
NKRO_ENABLE = yes
RGBLIGHT_ENABLE = yes

# oled
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
OLED_TRANSPORT = i2c

# SET TO no FOR PRODUCTION USE!
VIAL_INSECURE = no
