LTO_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no

KEY_OVERRIDE_ENABLE = no
LEADER_ENABLE = no
DYNAMIC_MACRO_ENABLE = no

AUDIO_ENABLE = no
MIDI_ENABLE = no
UNICODE_ENABLE = no
BLUETOOTH_ENABLE = no
SPLIT_KEYBOARD = no

BOOTMAGIC_ENABLE = yes
EXTRAKEY_ENABLE = no
COMBO_ENABLE = no
TAP_DANCE_ENABLE = yes
NKRO_ENABLE = yes
RGBLIGHT_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = ssd1306
OLED_TRANSPORT = i2c

#### SET TO no FOR PRODUCTION USE!
VIAL_INSECURE = no
